export default {


  getVisitsPerMonth: "Configration/getVisitsPerMonth",
  getVisitsPerMonthSuccess: "Configration/getVisitsPerMonthSuccess",
  addPlanType: "Configration/addPlanType",
  addPlanTypeError: "Configration/addPlanTypeError",
  updatePlanType: "Configration/updatePlanType",
  archivePlanType: "Configration/archivePlanType",
  addVisitPerMonth: "Configration/addVisitPerMonth",
  updateVisitPerMonth: "Configration/updateVisitPerMonth",
  archiveVisitPerMonth: "Configration/archiveVisitPerMonth",
  addVisitTimeSlot: "Configration/addVisitTimeSlot",
  updateVisitTimeSlot: "Configration/updateVisitTimeSlot",
  archiveVisitTimeSlot: "Configration/archiveVisitTimeSlot",
  visitTimeSlotErrors: "Configration/visitTimeSlotErrors",
  addVisitingCapacity: "Configration/addVisitingCapacity",
  getVisitingCapacity: "Configration/getVisitingCapacity",
  getVisitingCapacitySuccess: "Configration/getVisitingCapacitySuccess",
  addDaysSlots: "Configration/addDaysSlots",
  addDaysSlotsSuccess: "Configration/addDaysSlotsSuccess",
  getAllPlans: "Configration/getAllPlans",
  getAllPlansSuccess: "Configration/getAllPlansSuccess",
  getDays: "Configration/getDays",
  getDaySuccess: "Configration/getDaySuccess",
  getTimeSlotSuccess: "Visits/getTimeSlotSuccess",
  getTimeSlots: "Visits/getTimeSlots",
};
