export const REQUEST_SUCCESS_RESPONSE = "REQUEST_SUCCESS_RESPONSE";
export const REQUEST_ERROR_RESPONSE = "REQUEST_ERROR_RESPONSE";

export const GET_DRIVER_REQUEST = "GET_DRIVER_REQUEST";
export const GET_DRIVER_SUCCESS = "GET_DRIVER_SUCCESS";
export const GET_DRIVER_ERROR = "GET_DRIVER_ERROR";
export const UPDATE_DRIVER_REQUEST = "UPDATE_DRIVER_REQUEST";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";
export const UPDATE_DRIVER_ERROR = "UPDATE_DRIVER_ERROR";
export const ARCHIVE_DRIVER_REQUEST = "ARCHIVE_DRIVER_REQUEST";
export const ARCHIVE_DRIVER_SUCCESS = "ARCHIVE_DRIVER_SUCCESS";
export const ARCHIVE_DRIVER_ERROR = "ARCHIVE_DRIVER_ERROR";
export const ADD_DRIVER_REQUEST = "ADD_DRIVER_REQUEST";
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS";
export const ADD_DRIVER_ERROR = "ADD_DRIVER_ERROR";
export const SHOW_DRIVER_REQUEST = "SHOW_DRIVER_REQUEST";
export const SHOW_DRIVER_SUCCESS = "SHOW_DRIVER_SUCCESS";
export const SHOW_DRIVER_ERROR = "SHOW_DRIVER_ERROR";

export const COMMON_ERROR_MSG = "COMMON_ERROR_MSG";
export const COMMON_SUCCESS_MSG = "COMMON_SUCCESS_MSG";


export const GET_PASSANGER_REQUEST = "GET_PASSANGER_REQUEST";
export const GET_PASSANGER_SUCCESS = "GET_PASSANGER_SUCCESS";
export const GET_PASSANGER_ERROR = "GET_PASSANGER_ERROR";
export const UPDATE_PASSANGER_REQUEST = "UPDATE_PASSANGER_REQUEST";
export const UPDATE_PASSANGER_SUCCESS = "UPDATE_PASSANGER_SUCCESS";
export const UPDATE_PASSANGER_ERROR = "UPDATE_PASSANGER_ERROR";
export const ARCHIVE_PASSANGER_REQUEST = "ARCHIVE_PASSANGER_REQUEST";
export const ARCHIVE_PASSANGER_SUCCESS = "ARCHIVE_PASSANGER_SUCCESS";
export const ARCHIVE_PASSANGER_ERROR = "ARCHIVE_PASSANGER_ERROR";
export const ADD_PASSANGER_REQUEST = "ADD_PASSANGER_REQUEST";
export const ADD_PASSANGER_SUCCESS = "ADD_PASSANGER_SUCCESS";
export const ADD_PASSANGER_ERROR = "ADD_PASSANGER_ERROR";
export const SHOW_PASSANGER_REQUEST = "SHOW_PASSANGER_REQUEST";
export const SHOW_PASSANGER_SUCCESS = "SHOW_PASSANGER_SUCCESS";
export const SHOW_PASSANGER_ERROR = "SHOW_PASSANGER_ERROR";



export const GET_VEHICLE_REQUEST = "GET_VEHICLE_REQUEST";
export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS";
export const GET_VEHICLE_ERROR = "GET_VEHICLE_ERROR";
export const UPDATE_VEHICLE_REQUEST = "UPDATE_VEHICLE_REQUEST";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_ERROR = "UPDATE_VEHICLE_ERROR";
export const ARCHIVE_VEHICLE_REQUEST = "ARCHIVE_VEHICLE_REQUEST";
export const ARCHIVE_VEHICLE_SUCCESS = "ARCHIVE_VEHICLE_SUCCESS";
export const ARCHIVE_VEHICLE_ERROR = "ARCHIVE_VEHICLE_ERROR";
export const ADD_VEHICLE_REQUEST = "ADD_VEHICLE_REQUEST";
export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";
export const ADD_VEHICLE_ERROR = "ADD_VEHICLE_ERROR";
export const SHOW_VEHICLE_REQUEST = "SHOW_VEHICLE_REQUEST";
export const SHOW_VEHICLE_SUCCESS = "SHOW_VEHICLE_SUCCESS";
export const SHOW_VEHICLE_ERROR = "SHOW_VEHICLE_ERROR";


export const GET_TRANSFER_REQUEST = "GET_TRANSFER_REQUEST";
export const GET_TRANSFER_SUCCESS = "GET_TRANSFER_SUCCESS";
export const GET_TRANSFER_ERROR = "GET_TRANSFER_ERROR";
export const UPDATE_TRANSFER_REQUEST = "UPDATE_TRANSFER_REQUEST";
export const UPDATE_TRANSFER_SUCCESS = "UPDATE_TRANSFER_SUCCESS";
export const UPDATE_TRANSFER_ERROR = "UPDATE_TRANSFER_ERROR";
export const ARCHIVE_TRANSFER_REQUEST = "ARCHIVE_TRANSFER_REQUEST";
export const ARCHIVE_TRANSFER_SUCCESS = "ARCHIVE_TRANSFER_SUCCESS";
export const ARCHIVE_TRANSFER_ERROR = "ARCHIVE_TRANSFER_ERROR";
export const ADD_TRANSFER_REQUEST = "ADD_TRANSFER_REQUEST";
export const ADD_TRANSFER_SUCCESS = "ADD_TRANSFER_SUCCESS";
export const ADD_TRANSFER_ERROR = "ADD_TRANSFER_ERROR";
export const FILTER_TRANSFER_REQUEST = "ADD_TRANSFER_ERROR";
export const FILTER_TRANSFER_SUCCESS = "ADD_TRANSFER_ERROR";
export const FILTER_TRANSFER_ERROR = "ADD_TRANSFER_ERROR";
export const SHOW_TRANSFER_REQUEST = "SHOW_TRANSFER_REQUEST";
export const SHOW_TRANSFER_SUCCESS = "SHOW_TRANSFER_SUCCESS";
export const SHOW_TRANSFER_ERROR = "SHOW_TRANSFER_ERROR";